name: RAPA_CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ls -la
        run: ls -la
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./build/libs/*.war

      - uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Build and publish image to GCR
        uses: carbonchain/action-container-registry@v1.1
        with:
          project_id: ${{ secret.GCP_PROJECT_ID }}
          dockerfile: ./Dockerfile
          image: gcr.io/ ${{ secret.GCP_PROJECT_ID }}/rapa:latest
          service_account_key: ${{ secrets.GCLOUD_AUTH }}


      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: cluster-1
          location: us-central1-c
          credentials: ${{ secrets.GCP_SA_KEY }}
   
      - name: Deploy-Restart
        run: kubectl rollout restart deployment/was 

      - name: get-all
        run: kubectl get all